version: '3'
services:
  webapp:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/deploy
      - /deploy/node_modules
    ports:
      - "${PORT}:${CONTAINER_PORT}"
    command: yarn run start
    links:
      - redis
    environment:
      - CAT_API_KEY=${CAT_API_KEY}
      - PORT=8080
      - CONTAINER_PORT=8080
  redis:
    image: redis:3.2
